# Setup
title:        NanoPlayBoard
tagline:      Experimental and Educational Shield for Arduino Nano
baseurl:      ""
paginate:     1
permalink:    none

# Google Analytics
google_tracking_id: UA-84933832-1

# About/contact
authors:
  - name:       Antonio Morales
    url:        http://twitter.com/antonio1010mr
  - name:       José Juan Sánchez
    url:        http://josejuansanchez.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge